export const testData_ordersByType = {
    body: {
        ByDate: [
            {
                Date: '2022-12-16',
                Types: [
                    {
                        NotReadyCount: 37,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 136,
                        ReadyPercent: 78.61,
                    },
                    {
                        NotReadyCount: 80,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 160,
                        ReadyPercent: 66.67,
                    },
                    {
                        NotReadyCount: 10,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 21,
                        ReadyPercent: 67.74,
                    },
                ],
            },
            {
                Date: '2022-12-02',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 149,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 145,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 27,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-13',
                Types: [
                    {
                        NotReadyCount: 2,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 145,
                        ReadyPercent: 98.64,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 160,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 23,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-05',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 144,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 150,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 18,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-06',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 141,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 1,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 144,
                        ReadyPercent: 99.31,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 21,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-20',
                Types: [
                    {
                        NotReadyCount: 14,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 119,
                        ReadyPercent: 89.47,
                    },
                    {
                        NotReadyCount: 15,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 141,
                        ReadyPercent: 90.38,
                    },
                    {
                        NotReadyCount: 2,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 14,
                        ReadyPercent: 87.5,
                    },
                ],
            },
            {
                Date: '2022-12-21',
                Types: [
                    {
                        NotReadyCount: 126,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 11,
                        ReadyPercent: 8.03,
                    },
                    {
                        NotReadyCount: 156,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 4,
                        ReadyPercent: 2.5,
                    },
                    {
                        NotReadyCount: 18,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 1,
                        ReadyPercent: 5.26,
                    },
                ],
            },
            {
                Date: '2022-12-12',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 144,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 153,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 19,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-08',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 141,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 2,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 152,
                        ReadyPercent: 98.7,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 28,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-10',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 83,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 42,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 3,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-14',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 133,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 150,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 17,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-17',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 70,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 2,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 51,
                        ReadyPercent: 96.23,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 4,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-04',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 83,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 35,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 1,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-15',
                Types: [
                    {
                        NotReadyCount: 1,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 137,
                        ReadyPercent: 99.28,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 153,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 19,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-19',
                Types: [
                    {
                        NotReadyCount: 5,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 131,
                        ReadyPercent: 96.32,
                    },
                    {
                        NotReadyCount: 10,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 141,
                        ReadyPercent: 93.38,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 21,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-09',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 149,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 151,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 24,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-18',
                Types: [
                    {
                        NotReadyCount: 1,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 68,
                        ReadyPercent: 98.55,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 45,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 2,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-11',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 76,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 46,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 0,
                        ReadyPercent: null,
                    },
                ],
            },
            {
                Date: '2022-12-07',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 151,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 154,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 20,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-03',
                Types: [
                    {
                        NotReadyCount: 0,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 85,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 48,
                        ReadyPercent: 100,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 7,
                        ReadyPercent: 100,
                    },
                ],
            },
            {
                Date: '2022-12-01',
                Types: [
                    {
                        NotReadyCount: 1,
                        OrderType: 'P',
                        OrderTypeName: 'Пассажирские перевозки',
                        ReadyCount: 186,
                        ReadyPercent: 99.47,
                    },
                    {
                        NotReadyCount: 2,
                        OrderType: 'C',
                        OrderTypeName: 'Грузовые перевозки',
                        ReadyCount: 229,
                        ReadyPercent: 99.13,
                    },
                    {
                        NotReadyCount: 0,
                        OrderType: 'S',
                        OrderTypeName: 'Работа спец техники',
                        ReadyCount: 26,
                        ReadyPercent: 100,
                    },
                ],
            },
        ],
        FromDate: '2022-12-01',
        ToDate: '2022-12-21',
        Total: [
            {
                NotReadyCount: 187,
                OrderType: 'P',
                OrderTypeName: 'Пассажирские перевозки',
                ReadyCount: 2482,
                ReadyPercent: 92.99,
            },
            {
                NotReadyCount: 30,
                OrderType: 'S',
                OrderTypeName: 'Работа спец техники',
                ReadyCount: 316,
                ReadyPercent: 91.33,
            },
            {
                NotReadyCount: 268,
                OrderType: 'C',
                OrderTypeName: 'Грузовые перевозки',
                ReadyCount: 2454,
                ReadyPercent: 90.15,
            },
        ],
    },
    dt: '2022-12-21 16:14:05.189323+03',
    ref: '1f76b069-7521-49fe-85f8-c4a27a363934',
    sign: '32b6ab56f59ae8d70d30960c8e58abbd',
    time: '0:00:01.232248',
};
